[project]
name = "moj-dlt-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cloudpathlib>=0.21.1",
    "dlt[parquet]>=1.14.1",
]

[dependency-groups]
test = [
    "pytest>=8.4.1",
]
