---
name: Run Unit Test via Pytest

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: ['3.12']

        steps:
            - uses: actions/checkout@v4.2.2

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Set up Python ${{ matrix.python-version }}
              run: uv python install ${{ matrix.python-version }}

            - name: Install the project
              run: uv sync --group test

            - name: Run tests
              run: uv run pytest tests/unit -vv
